"""Small, explicit bilingual catalogue for the customer-facing portal."""
from django.conf import settings
from django.urls import reverse

from .plans import PLANS

COPY = {
    "de": {
        "title": "BetBoy – Sport verstehen. Bewusst entscheiden.",
        "description": "Sportanalysen, Modellprognosen und deine Tipps in einem übersichtlichen Workspace.",
        "skip": "Zum Inhalt", "features": "So funktioniert’s", "pricing": "Abos", "mobile": "Unterwegs",
        "login": "Einloggen", "register": "Konto erstellen", "account": "Mein Konto", "logout": "Abmelden",
        "eyebrow": "DEIN SPIELTAG. DEINE ANALYSE.",
        "hero_a": "Weniger Bauchgefühl.", "hero_b": "Mehr Spielverständnis.",
        "hero_text": "Form vergleichen. Chancen entdecken. Fundierter tippen.",
        "hero_cta": "Jetzt Abo wählen", "hero_secondary": "BetBoy kennenlernen",
        "hero_note": "Ab CHF 9.90 / Monat · Monatlich kündbar",
        "preview": "Produktvorschau", "illustration": "Illustratives Beispiel – kein aktueller Tipp",
        "workspace": "Dein Spieltag", "today": "Im Überblick", "model": "Modell", "match": "Spielanalyse",
        "example_home": "Heimteam", "example_away": "Gastteam", "example_market": "Beide Teams treffen",
        "example_reason": "Beide Angriffsreihen im Vergleich", "form": "Form", "statistics": "Statistik",
        "context": "Kontext", "detail": "Zahlen. Gründe. Gegenrisiken.",
        "sport_football": "Fußball", "sport_tennis": "Tennis", "sport_basketball": "Basketball",
        "sport_hockey": "Eishockey", "sport_esports": "E-Sport",
        "approach_label": "SO FUNKTIONIERT’S",
        "approach_title": "In drei Schritten\nzu deinem Überblick.",
        "feature1_title": "Spiele entdecken", "feature1_text": "Finde interessante Partien.",
        "feature2_title": "Form vergleichen", "feature2_text": "Sieh Form und Gegner im Vergleich.",
        "feature3_title": "Auswahl verstehen", "feature3_text": "Erkenne die Gründe für eine Auswahl.",
        "pricing_label": "EIN ABO. MEHR ÜBERBLICK.", "pricing_title": "Wähle dein BetBoy Abo.",
        "pricing_text": "Gleiche Analyse-Qualität in allen Abos.\nUnterschiedliche Funktionen. Dein Spielstil.",
        "per_month": "/ Monat", "currency": "CHF", "choose": "wählen", "recommended": "Empfohlen",
        "starter_desc": "Der smarte Einstieg.", "plus_desc": "Für alle, die mehr wollen.", "pro_desc": "Maximale Flexibilität.",
        "navigation": "Hauptnavigation", "menu": "Menü", "language_label": "Sprache",
        "hero_image_alt": "BetBoy auf einem natürlich proportionierten Smartphone, zwischen Fußballstadion und Tennisplatz. Illustrative Spiel- und Formansichten mit fiktiven Teams und Spielern.",
        "benefit1_title": "Klare Analysen", "benefit1_text": "statt Spekulation",
        "benefit2_title": "Mehr Kontext", "benefit2_text": "für bessere Entscheidungen",
        "benefit3_title": "Dein Überblick", "benefit3_text": "an jedem Spieltag",
        "month_navigation": "Monatsbilanz",
        "month_title": "Monatsbilanz · September 2026", "month_status": "Noch keine veröffentlichte Monatsbilanz.",
        "month_rate": "Trefferquote", "month_count": "Ausgewertete Tipps", "month_balance": "Bilanz", "month_unavailable": "Noch nicht veröffentlicht",
        "same_quality": "Gleiche Analyse-Qualität in allen Abos.", "choose_now": "Jetzt wählen",
        "closing_label": "BEREIT FÜR DEN NÄCHSTEN SPIELTAG?", "closing_cta": "Los geht’s",
        "risk_short": "18+ · Wetten können zum Verlust des Einsatzes führen.",
        "landing_saved": "Gespeicherte Tipps", "landing_search": "Eigene Suche", "landing_riskobet": "RisikoBet",
        "landing_live": "Live", "landing_daily3": "Daily3", "landing_15k": "15K",
        "automatic": "Automatischer Wettfinder", "saved": "Tipps speichern & verfolgen", "search": "Eigene Spiel- und Marktsuche",
        "riskobet": "RisikoBet: Außenseiter-Szenarien", "live": "Live-Bereich", "daily3": "Daily3-Tagesplan", "15k": "15K-Challenge",
        "includes_starter": "Alles aus Starter", "includes_plus": "Alles aus Plus",
        "pricing_note": "Monatliche Verlängerung. Kündigung zum Ende des bezahlten Zeitraums. Keine Wetteinsätze im Abo enthalten.",
        "availability": "Daten und verfügbare Spiele unterscheiden sich je Sportart.",
        "mobile_label": "EIN KONTO. DEIN SPIELTAG.", "mobile_title": "Auch unterwegs\nalles im Blick.",
        "mobile_text": "Die Website passt auf dein Smartphone. Native Apps für iOS und Android sind geplant und noch nicht im Store verfügbar.",
        "mobile_badge": "Web · Mobil optimiert", "coming": "In Vorbereitung", "same_account": "Gemeinsames Kundenkonto vorgesehen",
        "faq_title": "Kurz beantwortet.", "faq1_q": "Sind die Tipps im Pro-Abo besser?", "faq1_a": "Nein. Alle Abos verwenden dieselben Modelle. Sie unterscheiden sich durch die verfügbaren Funktionen.",
        "faq2_q": "Kann ich direkt bei BetBoy wetten?", "faq2_a": "Nein. BetBoy ist eine Analyse-App, kein Buchmacher. Das Abo enthält keine Wetteinsätze und nimmt keine Wetten an.",
        "faq3_q": "Wie kann ich mein Abo kündigen?", "faq3_a": "Web-Abos verwaltest du nach dem Kauf im Kundenkonto über Stripe. Der Zugang bleibt bis zum Ende des bezahlten Zeitraums bestehen.",
        "footer": "Sport verstehen. Bewusst entscheiden.", "risk": "18+. Modellwerte sind Schätzungen. Wetten können zum Verlust des Einsatzes führen.",
        "privacy": "Datenschutz", "terms": "AGB", "legal": "Anbieterinformationen",
        "preview_notice": "Vorschau · Verkauf noch nicht gestartet", "legal_pending": "Die rechtlichen Anbieterinformationen werden vor Verkaufsstart ergänzt.",
        "auth_eyebrow": "WILLKOMMEN BEI BETBOY", "login_title": "Schön, dass du da bist.", "login_text": "Melde dich mit deinem BetBoy-Konto an.",
        "register_title": "Dein Spieltag beginnt hier.", "register_text": "Konto erstellen, E-Mail bestätigen, Abo wählen.",
        "email": "E-Mail-Adresse", "password": "Passwort", "repeat_password": "Passwort wiederholen", "password_help": "Mindestens 12 Zeichen. Verwende ein eigenes, langes Passwort.",
        "accept_terms": "Ich bin mindestens 18 Jahre alt und akzeptiere die AGB. Die Datenschutzhinweise habe ich gelesen.",
        "password_mismatch": "Die Passwörter stimmen nicht überein.", "login_error": "Anmeldung nicht möglich. Prüfe E-Mail, Passwort und die Bestätigung deiner E-Mail-Adresse.",
        "no_account": "Noch kein Konto?", "have_account": "Schon registriert?", "forgot": "Passwort vergessen?",
        "register_closed": "Die Registrierung öffnet mit dem Verkaufsstart. Du kannst dir die Abos bereits ansehen.",
        "selected_plan": "Ausgewähltes Abo", "change_plan": "Abo vergleichen", "no_charge": "Die Registrierung kostet nichts. Ein Abo wird erst im Zahlungsfenster abgeschlossen.",
        "check_mail": "Prüfe dein Postfach.", "activation_sent": "Wenn deine Adresse für eine Registrierung verwendet werden kann, erhältst du einen Bestätigungslink. Bei einem bestehenden Konto kannst du dein Passwort zurücksetzen.",
        "activation_subject": "BetBoy: E-Mail-Adresse bestätigen", "activation_body": "Bestätige deine E-Mail-Adresse über diesen Link. Er ist eine Stunde gültig.",
        "activate_title": "E-Mail-Adresse bestätigen", "activate_text": "Bestätige diese Adresse, um dein BetBoy-Konto zu aktivieren.", "activate": "Adresse bestätigen",
        "activated": "Deine E-Mail-Adresse ist bestätigt. Du kannst dich jetzt einloggen.", "invalid_link": "Dieser Link ist ungültig oder abgelaufen. Bitte fordere einen neuen Link an.",
        "reset_title": "Wieder Zugang bekommen.", "reset_text": "Wir senden dir einen Link, mit dem du ein neues Passwort festlegen kannst.", "reset_send": "Link anfordern",
        "reset_sent": "Falls für diese Adresse ein bestätigtes Konto besteht, erhältst du einen Link zum Zurücksetzen.",
        "reset_subject": "BetBoy: Passwort zurücksetzen", "reset_body": "Über diesen Link kannst du dein Passwort zurücksetzen. Er ist eine Stunde gültig. Wenn du das nicht angefordert hast, ignoriere diese E-Mail.",
        "new_password": "Neues Passwort festlegen", "save_password": "Passwort speichern", "password_changed": "Dein Passwort wurde geändert. Bitte melde dich erneut an.",
        "limited": "Zu viele Versuche. Bitte versuche es in 15 Minuten erneut.", "mail_unavailable": "E-Mails können gerade nicht versendet werden. Bitte versuche es später erneut.",
        "account_title": "Dein BetBoy.", "account_text": "Konto, Zugang und Abo an einem Ort.", "current_plan": "Dein Zugang", "no_plan": "Noch kein aktives Abo",
        "open_app": "BetBoy öffnen", "manage": "Abo & Rechnungen", "choose_plan": "Abo auswählen", "checkout": "Weiter zu Stripe",
        "billing_unavailable": "Der Abo-Verkauf ist noch nicht geöffnet. Es wird nichts abgebucht.", "billing_error": "Der Bezahlvorgang konnte nicht geöffnet werden. Bei einem bestehenden Abo nutze „Abo & Rechnungen“; sonst versuche es später erneut.",
        "payment_returned": "Zahlungsfenster geschlossen. Dein Zugang erscheint, sobald Stripe die Zahlung bestätigt hat.",
        "refresh": "Status aktualisieren", "paid_until": "Bezahlt bis", "cancel_end": "Endet zum Ablauf des bezahlten Zeitraums",
        "portal_wait": "Der App-Zugang wird zum Verkaufsstart aktiviert.", "session_expired": "Deine Sitzung ist abgelaufen. Lade die Seite neu und versuche es erneut.",
        "back": "Zur Startseite", "not_found": "Diese Seite wurde nicht gefunden.",
    },
    "en": {
        "title": "BetBoy – Understand the game. Make your own call.",
        "description": "Sports analysis, model forecasts and your picks in one clear workspace.",
        "skip": "Skip to content", "features": "How it works", "pricing": "Plans", "mobile": "On the go",
        "login": "Log in", "register": "Create account", "account": "My account", "logout": "Log out",
        "eyebrow": "YOUR MATCHDAY. YOUR ANALYSIS.",
        "hero_a": "Less guesswork.", "hero_b": "More game insight.",
        "hero_text": "Compare form. Discover opportunities. Make informed picks.",
        "hero_cta": "Choose your plan", "hero_secondary": "Explore BetBoy",
        "hero_note": "From CHF 9.90 / month · Cancel monthly",
        "preview": "Product preview", "illustration": "Illustrative example — not a current pick",
        "workspace": "Your matchday", "today": "At a glance", "model": "Model", "match": "Match analysis",
        "example_home": "Home team", "example_away": "Away team", "example_market": "Both teams to score",
        "example_reason": "Comparing both attacks", "form": "Form", "statistics": "Statistics",
        "context": "Context", "detail": "Numbers. Reasons. Counter-risks.",
        "sport_football": "Football", "sport_tennis": "Tennis", "sport_basketball": "Basketball",
        "sport_hockey": "Ice hockey", "sport_esports": "Esports",
        "approach_label": "HOW IT WORKS",
        "approach_title": "Your overview.\nThree simple steps.",
        "feature1_title": "Discover games", "feature1_text": "Find interesting matchups.",
        "feature2_title": "Compare form", "feature2_text": "Put form and opponents in perspective.",
        "feature3_title": "Understand the pick", "feature3_text": "See the reasons behind a selection.",
        "pricing_label": "ONE PLAN. MORE PERSPECTIVE.", "pricing_title": "Choose your BetBoy plan.",
        "pricing_text": "Same analysis quality in every plan.\nDifferent tools. Your style of play.",
        "per_month": "/ month", "currency": "CHF", "choose": "Choose", "recommended": "Recommended",
        "starter_desc": "A smart way to start.", "plus_desc": "For fans who want more.", "pro_desc": "Maximum flexibility.",
        "navigation": "Main navigation", "menu": "Menu", "language_label": "Language",
        "hero_image_alt": "BetBoy on a naturally proportioned smartphone, between a football stadium and tennis court. Illustrative game and form views with fictional teams and players.",
        "benefit1_title": "Clear analysis", "benefit1_text": "not speculation",
        "benefit2_title": "More context", "benefit2_text": "for informed decisions",
        "benefit3_title": "Your overview", "benefit3_text": "every matchday",
        "month_navigation": "Monthly results",
        "month_title": "Monthly results · September 2026", "month_status": "No published monthly results yet.",
        "month_rate": "Win rate", "month_count": "Settled picks", "month_balance": "Results", "month_unavailable": "Not published yet",
        "same_quality": "Same analysis quality in every plan.", "choose_now": "Choose now",
        "closing_label": "READY FOR YOUR NEXT MATCHDAY?", "closing_cta": "Let’s go",
        "risk_short": "18+ · Betting can result in loss of your stake.",
        "landing_saved": "Saved picks", "landing_search": "Custom search", "landing_riskobet": "RisikoBet",
        "landing_live": "Live", "landing_daily3": "Daily3", "landing_15k": "15K",
        "automatic": "Automatic match finder", "saved": "Save & track your picks", "search": "Custom game & market search",
        "riskobet": "RisikoBet: underdog scenarios", "live": "Live workspace", "daily3": "Daily3 daily plan", "15k": "15K Challenge",
        "includes_starter": "Everything in Starter", "includes_plus": "Everything in Plus",
        "pricing_note": "Renews monthly. Cancel at the end of your paid period. Betting stakes are not included.",
        "availability": "Data and available games vary by sport.",
        "mobile_label": "ONE ACCOUNT. YOUR MATCHDAY.", "mobile_title": "Take the overview\nwith you.",
        "mobile_text": "The website works on your phone. Native iOS and Android apps are planned and are not yet available in the stores.",
        "mobile_badge": "Web · Mobile-ready", "coming": "In preparation", "same_account": "Shared customer account planned",
        "faq_title": "A few quick answers.", "faq1_q": "Are Pro picks better?", "faq1_a": "No. Every plan uses the same models. Plans differ in the features you can access.",
        "faq2_q": "Can I place a bet on BetBoy?", "faq2_a": "No. BetBoy is an analysis app, not a bookmaker. Your subscription includes no betting stakes and BetBoy does not accept bets.",
        "faq3_q": "How do I cancel my subscription?", "faq3_a": "Manage web subscriptions through Stripe from your customer account after purchase. Access continues until the end of your paid period.",
        "footer": "Understand the game. Make your own call.", "risk": "18+. Model estimates can be wrong. Betting can result in loss of your stake.",
        "privacy": "Privacy", "terms": "Terms", "legal": "Provider information",
        "preview_notice": "Preview · Sales have not opened yet", "legal_pending": "Provider and legal information will be completed before sales open.",
        "auth_eyebrow": "WELCOME TO BETBOY", "login_title": "Good to see you.", "login_text": "Sign in with your BetBoy account.",
        "register_title": "Your matchday starts here.", "register_text": "Create an account, confirm your email, choose a plan.",
        "email": "Email address", "password": "Password", "repeat_password": "Repeat password", "password_help": "At least 12 characters. Use a unique, long password.",
        "accept_terms": "I am at least 18 and accept the Terms. I have read the Privacy notice.",
        "password_mismatch": "The passwords do not match.", "login_error": "Unable to sign in. Check your email, password and that you have confirmed your email address.",
        "no_account": "New to BetBoy?", "have_account": "Already registered?", "forgot": "Forgot password?",
        "register_closed": "Registration opens when sales launch. You can explore the plans now.",
        "selected_plan": "Selected plan", "change_plan": "Compare plans", "no_charge": "Creating an account is free. You only subscribe when you complete checkout.",
        "check_mail": "Check your inbox.", "activation_sent": "If this address can be registered, you will receive a confirmation link. If you already have an account, you can reset your password.",
        "activation_subject": "BetBoy: confirm your email address", "activation_body": "Confirm your email address using this link. It is valid for one hour.",
        "activate_title": "Confirm your email address", "activate_text": "Confirm this address to activate your BetBoy account.", "activate": "Confirm address",
        "activated": "Your email address is confirmed. You can now log in.", "invalid_link": "This link is invalid or has expired. Please request a new link.",
        "reset_title": "Get back into your account.", "reset_text": "We will send a link so you can set a new password.", "reset_send": "Send reset link",
        "reset_sent": "If a confirmed account exists for this address, you will receive a password reset link.",
        "reset_subject": "BetBoy: reset your password", "reset_body": "Use this link to reset your password. It is valid for one hour. If you did not request this, ignore this email.",
        "new_password": "Set a new password", "save_password": "Save password", "password_changed": "Your password has been changed. Please log in again.",
        "limited": "Too many attempts. Please try again in 15 minutes.", "mail_unavailable": "Email is temporarily unavailable. Please try again later.",
        "account_title": "Your BetBoy.", "account_text": "Your account, access and subscription in one place.", "current_plan": "Your access", "no_plan": "No active subscription yet",
        "open_app": "Open BetBoy", "manage": "Subscription & invoices", "choose_plan": "Choose a plan", "checkout": "Continue to Stripe",
        "billing_unavailable": "Subscription sales have not opened yet. You will not be charged.", "billing_error": "Unable to open checkout. For an existing subscription, use “Subscription & invoices”; otherwise please try again later.",
        "payment_returned": "Checkout closed. Your access will appear after Stripe confirms your payment.",
        "refresh": "Refresh status", "paid_until": "Paid until", "cancel_end": "Ends at the end of your paid period",
        "portal_wait": "App access will be enabled when sales open.", "session_expired": "Your session has expired. Reload the page and try again.",
        "back": "Back to home", "not_found": "This page could not be found.",
    },
}


def context(request):
    lang = getattr(request, "LANGUAGE_CODE", "de")
    words = COPY[lang]
    other = "en" if lang == "de" else "de"
    switch = reverse("home", kwargs={"lang": other})
    match = request.resolver_match
    if match and match.url_name in {"home", "login", "register", "account", "reset"}:
        switch = reverse(match.url_name, kwargs={"lang": other})
    cards = []
    for key, plan in PLANS.items():
        features = plan["features"] if key == "starter" else (("search", "riskobet") if key == "plus" else ("live", "daily3", "15k"))
        cards.append({**plan, "key": key, "description": words[f"{key}_desc"],
                      "included": "" if key == "starter" else words["includes_starter" if key == "plus" else "includes_plus"],
                      "labels": [words[feature] for feature in features],
                      "feature_details": [{"short": words.get(f"landing_{feature}", words[feature]),
                                           "full": words[feature]} for feature in plan["features"]]})
    return {
        "t": words, "lang": lang, "switch_language": switch, "other_lang": other,
        "plans": cards, "legal_ready": settings.LEGAL_READY,
        "legal_url": settings.LEGAL_URL, "privacy_url": settings.PRIVACY_URL, "terms_url": settings.TERMS_URL,
        "sales_open": settings.REGISTRATION_OPEN and settings.LEGAL_READY,
        "hero_asset": f"portal/editorial/hero{'-en' if lang == 'en' else ''}.webp",
        "hero_small_asset": f"portal/editorial/hero{'-en' if lang == 'en' else ''}-small.webp",
        "stadium_asset": f"portal/editorial/stadium{'-en' if lang == 'en' else ''}.webp",
        "stadium_small_asset": f"portal/editorial/stadium{'-en' if lang == 'en' else ''}-small.webp",
    }
