[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = true

[theme]
base = "light"
primaryColor = "#16784b"
backgroundColor = "#f6f7f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#202428"
font = "sans-serif"
